name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^10.2.0
  drift: ^2.28.1
  shared_preferences: ^2.2.3
  drift_flutter: ^0.2.5
  path_provider: ^2.1.5
  path: ^1.8.2
  just_audio: ^0.10.4            # Full-featured audio playback with gapless, streaming, file, playlist support — latest was released Jun 5 2025 :contentReference[oaicite:1]{index=1}
  audio_service: ^0.18.0         # Background playback & notification handling (usually paired with just_audio)
  audio_session: ^0.1.21         # Proper audio session management for background audio

  metadata_god: ^1.0.0           # Read/write audio tags (ID3/mp4/FLAC), published ~9 months ago :contentReference[oaicite:3]{index=3}

  crypto: ^3.0.3
  uuid: ^4.2.1
  

  dio: ^5.8.0+1                    # HTTP client for fetching from APIs like Last.fm and Genius (widely used)
  json_serializable: ^6.6.0      # Automatic JSON model generation (facilitates parsing API responses)

  fl_chart: ^1.0.0  
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  palette_generator: ^0.3.3+7
  html: ^0.15.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.28.1
  build_runner: ^2.6.0
  custom_lint: ^0.8.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  fonts:
    - family: Sora
      fonts:
        - asset: assets/fonts/Sora-VariableFont_wght.ttf
          weight: 400
        - asset: assets/fonts/Sora-VariableFont_wght.ttf
          weight: 700

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon_logo.png"